name: Deploy to GAE

on: [push, workflow_dispatch ]

jobs:
  deploy:
    name: Deploying to Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.8.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"